# Generated by Django 3.2.7 on 2021-09-13 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210913_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='polygon_id',
            new_name='text_polygon_id',
        ),
    ]
